name: internship_task
description: A Flutter project for internship assignment
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (still needed for phone auth)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  # HTTP client for REST API (json-server)
  http: ^1.2.2

  # State management
  get: ^4.6.6

  # Country phone input
  intl_phone_field: ^3.2.0

  # Icons & material
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (create an assets/ folder in root if you plan to add images/fonts later)
  assets:
    - assets/
