name: internship_task
description: A Flutter project for internship assignment
publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Upgrade Firebase dependencies
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # HTTP client for REST API
  http: ^1.2.2

  # State management
  get: ^4.6.6

  # Country phone input field
  intl_phone_field: ^3.2.0

  # Icons & material design
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # ✅ also bump lint to latest

flutter:
  uses-material-design: true

  assets:
    - assets/
