// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2G0lX47yh1sbcJZFRKp0k5gyzMEZ4vSU',
    appId: '1:272203851951:web:2388412fdeb0140e24cc5a',
    messagingSenderId: '272203851951',
    projectId: 'internship-a3635',
    authDomain: 'internship-a3635.firebaseapp.com',
    storageBucket: 'internship-a3635.firebasestorage.app',
    measurementId: 'G-7YNR4TL4TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4-zQQvWnLliTc5byAxFinvtPLwgAQtzA',
    appId: '1:272203851951:android:1165435c2c78ea4f24cc5a',
    messagingSenderId: '272203851951',
    projectId: 'internship-a3635',
    storageBucket: 'internship-a3635.firebasestorage.app',
  );

}