import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';   // auto-generated by FlutterFire CLI
import 'controllers/auth_controller.dart';
import 'views/phone_auth_page.dart';
import 'views/otp_screen.dart';
import 'views/object_list_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase with web config
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  Get.put(AuthController()); // Inject AuthController
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Internship Task',
      initialRoute: "/phone",
      getPages: [
        GetPage(name: "/phone", page: () => PhoneAuthPage()),
        GetPage(name: "/otp", page: () => OTPScreen()),
        GetPage(name: "/dashboard", page: () => const ObjectListPage()),
      ],
    );
  }
}